### ISSUE TITLE
Benchmarking procedure

### ISSUE THREAD

**Issue by kvrigor** [kvrigor/SortingDemo#4]
* Test the sorting algorithms on three dataset sizes: 100, 500, and 1000 elements.
* For dataset size=100, display both unsorted and sorted data in a 10x10 matrix format.
* On the same dataset, execute each sorting algorithm twice 
    - 1st  sort: random numbers between 1 and 999
    - 2nd sort: take the sorted data from 1st sort, then swap the 19th and 20th element
    - Display the number of comparisons and moves necessary to order the list. Analyze **each loop limit 
       condition test** and **each selection statement**. Note the ff:
        + All loops require a count increment in their body.
        + Pretest loop (while and for) also require a count increment either before (recommended) or after 
            the loop to count the last test.
        + It is suggested to use [comma operators](http://www.cplusplus.com/doc/tutorial/operators/) for counting 
            `while ((count++,a) && (count++, b))`

**Comment by leandroUmali** [comment]
Anu this Paul?
