### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by chesterlbtan** [kvrigor/SortingDemo#5]
Lots of error in my side.

![image](https://cloud.githubusercontent.com/assets/22214030/26059041/e097effe-39b2-11e7-993b-3a9fe14c4253.png)

**Comment by kvrigor** [comment]
Fixed in e2853d080e2c337197b775f1d9387da2926d252f via [this solution](https://stackoverflow.com/questions/13613295/how-can-i-compile-c11-code-with-orwell-dev-c#13634404)

![image](https://cloud.githubusercontent.com/assets/17194936/26095887/e3c51874-3a51-11e7-96e5-132fa4072386.png)

**Comment by chesterlbtan** [comment]
:+1:
